# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

builds:
  - builder: rust
    flags:
      - --release
    targets:
      # FIXME: - x86_64-unknown-linux-gnu
      # FIXME: - x86_64-apple-darwin
      - x86_64-pc-windows-gnu
      - aarch64-unknown-linux-gnu
      # FIXME: - aarch64-apple-darwin

signs:
  - cmd: cosign
    certificate: "${artifact}.pem"
    artifacts: checksum
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes"

dockers:
  - image_templates:
      - "ghcr.io/eigenein/mrktpltsbot:{{ .Tag }}-arm64"
    goarch: arm64
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"

docker_manifests:
  - name_template: "ghcr.io/eigenein/mrktpltsbot:{{ .Tag }}"
    image_templates:
      - "ghcr.io/eigenein/mrktpltsbot:{{ .Tag }}-arm64"

docker_signs:
  - cmd: cosign
    artifacts: manifests
    args:
      - "sign"
      - "${artifact}"
      - "--yes"

changelog:
  sort: asc

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
